version: '3.8'

services:
  db:
    image: mysql:5.6
    command:
      - --innodb_file_per_table
      - --innodb_file_format=Barracuda
      - --innodb_large_prefix
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
